export default class GraphTransactionBuilder {
    constructor(sdk: any, graphGuid: any, options?: {});
    _sdk: any;
    graphGuid: any;
    maxOperations: any;
    timeoutSeconds: any;
    operations: any[];
    withMaxOperations(maxOperations: any): this;
    withTimeoutSeconds(timeoutSeconds: any): this;
    add(operation: any): this;
    create(objectType: any, payload: any): this;
    update(objectType: any, payload: any, guid?: any): this;
    delete(objectType: any, guid: any): this;
    attach(objectType: any, payload: any, guid?: any): this;
    detach(objectType: any, guid: any): this;
    upsert(objectType: any, payload: any, guid?: any): this;
    createNode(payload: any): this;
    updateNode(payload: any, guid?: any): this;
    deleteNode(guid: any): this;
    upsertNode(payload: any, guid?: any): this;
    createEdge(payload: any): this;
    updateEdge(payload: any, guid?: any): this;
    deleteEdge(guid: any): this;
    upsertEdge(payload: any, guid?: any): this;
    createLabel(payload: any): this;
    updateLabel(payload: any, guid?: any): this;
    deleteLabel(guid: any): this;
    attachLabel(payload: any, guid?: any): this;
    detachLabel(guid: any): this;
    upsertLabel(payload: any, guid?: any): this;
    createTag(payload: any): this;
    updateTag(payload: any, guid?: any): this;
    deleteTag(guid: any): this;
    attachTag(payload: any, guid?: any): this;
    detachTag(guid: any): this;
    upsertTag(payload: any, guid?: any): this;
    createVector(payload: any): this;
    updateVector(payload: any, guid?: any): this;
    deleteVector(guid: any): this;
    attachVector(payload: any, guid?: any): this;
    detachVector(guid: any): this;
    upsertVector(payload: any, guid?: any): this;
    build(): {
        MaxOperations: any;
        TimeoutSeconds: any;
        Operations: any[];
    };
    execute(cancellationToken: any): Promise<any>;
    _payloadOperation(operationType: any, objectType: any, payload: any, guid?: any): this;
}
